In [1]:
import numpy as np

In [2]:
v=np.array([1,-1,2])  #vector is 1D array
w=np.array([2,5,2])

In [8]:
v.shape

(3,)

In [10]:
v.ndim

1

In [3]:
print(v+w)

[3 4 4]


In [4]:
print(v-w)

[-1 -6  0]


In [5]:
#scalar Mul:
print(3*v)

[ 3 -3  6]


In [6]:
#to find length of vector

print(np.linalg.norm(v))
# linalg(linear algebra) sub package
# norm --> to find length of vector

2.449489742783178


In [7]:
s=np.dot(v,w)
print(s)

1
