In [1]:
import numpy as np

In [7]:
P=np.array([[1,7],
            [2,1],
            [3,2]])   # 2darray --matrix
Q=np.array([[1,1],
            [1,-1],
            [1,0]])
print(P)
print(Q)

[[1 7]
 [2 1]
 [3 2]]
[[ 1  1]
 [ 1 -1]
 [ 1  0]]


In [10]:
C1=np.add(P,Q)    # addition of 2 matrices
print(C1)

[[2 8]
 [3 0]
 [4 2]]


In [11]:
C2=np.subtract(P,Q)   # subtraction of 2 matrices
print(C2)

[[0 6]
 [1 2]
 [2 2]]


In [12]:
R=np.array([[1,3,1],
            [1,0,1]])
print(R)

[[1 3 1]
 [1 0 1]]


In [14]:
C2=np.dot(P,R)    # dot product of 2 matrices
print(C2)

[[8 3 8]
 [3 6 3]
 [5 9 5]]


In [15]:
np.linalg.det(C2)  # to find determinant of matrix
# here C2 is singular matrix

0.0

In [16]:
np.linalg.inv(C2)  # error becoz C2 is singular matrix

LinAlgError: Singular matrix

In [17]:
M=np.array([[1,-1],
            [2,3]])
print(M)

[[ 1 -1]
 [ 2  3]]


In [18]:
np.linalg.inv(M)   #inverse of matrix

array([[ 0.6,  0.2],
       [-0.4,  0.2]])