In [2]:
import numpy as np

In [4]:
v1 = [1,2,3] #vector is 1D array
v2 = [10,20,30]
v3 = [[12],
      [13],
      [14]]

v1 = np.array(v1)
v2 = np.array(v2)
v3 = np.array(v3)

print("Horizontal vectors: ")
print(v1)
print(v2)
print("Vertical vector: ")
print(v3)

Horizontal vectors: 
[1 2 3]
[10 20 30]
Vertical vector: 
[[12]
 [13]
 [14]]


In [7]:
print(v1.shape)
print(v1.ndim)

(3,)
1


In [5]:
print("Vector Addition: ", v1+v2)

print("Vector subtraction: ", v1-v2)

scalar = 2
print("Vector multiplication with scalar: ", scalar*v1)

Vector Addition:  [11 22 33]
Vector subtraction:  [ -9 -18 -27]
Vector multiplication with scalar:  [2 4 6]


In [6]:
# Dot product
print("Dot Product: ", np.dot(v1,v2))

# Cross Product
print("Cross Product: ", np.cross(v1,v2))

Dot Product:  140
Cross Product:  [0 0 0]
