In [1]:
import numpy as np,pandas as pd
import seaborn as sns

In [2]:
df=sns.load_dataset('tips')
df.head(6)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4

In [3]:
df=df.dropna()
df=df.drop(columns='smoker')
df.head()

total_bill   tip     sex  day    time  size
0       16.99  1.01  Female  Sun  Dinner     2
1       10.34  1.66    Male  Sun  Dinner     3
2       21.01  3.50    Male  Sun  Dinner     3
3       23.68  3.31    Male  Sun  Dinner     2
4       24.59  3.61  Female  Sun  Dinner     4

In [4]:
df=pd.get_dummies(df,drop_first=True)
df.head()

total_bill   tip  size  sex_Female  day_Fri  day_Sat  day_Sun  time_Dinner
0       16.99  1.01     2           1        0        0        1            1
1       10.34  1.66     3           0        0        0        1            1
2       21.01  3.50     3           0        0        0        1            1
3       23.68  3.31     2           0        0        0        1            1
4       24.59  3.61     4           1        0        0        1            1

In [5]:
X=df.drop(columns='sex_Female')
y=df['sex_Female']

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.2,random_state=58)
print('shape of X_train=',X_train.shape)
print('shape of X_test=',X_test.shape)
print('shape of y_train=',y_train.shape)
print('shape of y_test=',y_test.shape)

shape of X_train= (195, 7)
shape of X_test= (49, 7)
shape of y_train= (195,)
shape of y_test= (49,)


In [7]:
from sklearn.preprocessing import MinMaxScaler
mms=MinMaxScaler()
mms.fit(X_train)
X_train=mms.transform(X_train)
mms.fit(X_test)
X_test=mms.transform(X_test)

In [8]:
from sklearn.linear_model import LogisticRegression

In [9]:
lr=LogisticRegression()
lr.fit(X_train,y_train)

LogisticRegression()

In [11]:
lr.coef_

array([[-0.84203344, -0.33678228, -0.30400638,  0.10309794, -0.14789387,
        -0.61958017, -0.3867893 ]])

In [12]:
lr.intercept_

array([0.28019379])

In [13]:
lr.predict_proba(X_test)

array([[0.74288155, 0.25711845],
       [0.67639327, 0.32360673],
       [0.63181305, 0.36818695],
       [0.89255874, 0.10744126],
       [0.75255921, 0.24744079],
       [0.74133469, 0.25866531],
       [0.75998709, 0.24001291],
       [0.62648276, 0.37351724],
       [0.60170878, 0.39829122],
       [0.63573408, 0.36426592],
       [0.45120143, 0.54879857],
       [0.5945761 , 0.4054239 ],
       [0.72499295, 0.27500705],
       [0.50456007, 0.49543993],
       [0.8066957 , 0.1933043 ],
       [0.74910866, 0.25089134],
       [0.84370645, 0.15629355],
       [0.45448287, 0.54551713],
       [0.77165992, 0.22834008],
       [0.53697232, 0.46302768],
       [0.4964853 , 0.5035147 ],
       [0.52847362, 0.47152638],
       [0.66095755, 0.33904245],
       [0.63901415, 0.36098585],
       [0.49351339, 0.50648661],
       [0.50087439, 0.49912561],
       [0.47843678, 0.52156322],
       [0.58739966, 0.41260034],
       [0.80407645, 0.19592355],
       [0.44766743, 0.55233257],
       [0.

In [14]:
lr.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0], dtype=uint8)

In [15]:
lr.score(X_test,y_test)

0.5714285714285714