In [1]:
#-------------------------------svr------------------------------------------


import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r'../Useful data/Bangalore_House_Cleaned_data.csv')
df.head()

bath  balcony  price  total_sqft_int  bhk  price_per_sqft  \
0   3.0      2.0  150.0          1672.0    3     8971.291866   
1   3.0      3.0  149.0          1750.0    3     8514.285714   
2   3.0      2.0  150.0          1750.0    3     8571.428571   
3   2.0      2.0   40.0          1250.0    2     3200.000000   
4   2.0      2.0   83.0          1200.0    2     6916.666667   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                              1                        0   
1                              0                        1   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   area_typePlot  Area  availability_Ready To Move  ...  \
0                    0                           1  ...   
1                    0                           1  ...   
2                    0                           1  ...   
3                    0                           1  ...   
4                    1                           1  ...   

   location_Kalena Agrahara  location_Horamavu Agara  location_Vidyaranyapura  \
0                         0                        0                        0   
1                         0                        0                        0   
2                         0                        0                        0   
3                         0                        0                        0   
4                         0                        0                        0   

   location_BTM 2nd Stage  location_Hebbal Kempapura  location_Hosur Road  \
0                       0                          0                    0   
1                       0                          0                    0   
2                       0                          0                    0   
3                       0                          0                    0   
4                       0                          0                    0   

   location_Horamavu Banaswadi  location_Domlur  location_Mahadevpura  \
0                            0                0                     0   
1                            0                0                     0   
2                            0                0                     0   
3                            0                0                     0   
4                            0                0                     0   

   location_Tumkur Road  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  

[5 rows x 108 columns]

In [3]:
X=df.drop(columns=['price'])
y=df['price']
print('shape of X=',X.shape)
print('shape of y=',y.shape)

shape of X= (7120, 107)
shape of y= (7120,)


In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.3,random_state=58)

In [5]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(X_train)
X_train=sc.transform(X_train)
X_test=sc.transform(X_test)

In [6]:
from sklearn.svm import SVR

In [21]:
svr_rbf=SVR(kernel='rbf',gamma=.01,C=1.5)
svr_rbf.fit(X_train,y_train)
svr_rbf.score(X_test,y_test)

0.272781510290516

In [14]:
svr_linear=SVR(kernel='linear',C=1)
svr_linear.fit(X_train,y_train)
svr_linear.score(X_test,y_test)

0.7364314047105684

In [18]:
svr_poly=SVR(kernel='poly',degree=2,gamma=.1)
svr_poly.fit(X_train,y_train)
svr_poly.score(X_test,y_test)

0.8784155020103599

In [10]:
X_test[0]

array([-1.61558984,  0.54976467, -0.77825502, -0.5503044 ,  0.49029794,
        0.56931825, -0.47071077, -0.24901254,  0.51662744, -0.18329217,
       -0.16558088, -0.1550466 , -0.12276515, -0.13013577, -0.13250731,
       -0.12526719, -0.12021421, -0.12853209, -0.12853209, -0.11584511,
       -0.10850926, -0.10268101, -0.11314714, -0.11223415, -0.09437628,
       -0.08994785, -0.0888074 , -0.08765259, -0.09437628, -0.08765259,
       -0.07911279, -0.0888074 , -0.07911279, -0.07781846, -0.07911279,
       -0.0751646 , -0.0751646 , -0.06658601, -0.07100239, -0.07100239,
       -0.07241581, -0.07380273, -0.06504853, -0.0751646 , -0.07781846,
       -0.07380273, -0.07781846, -0.06956083, -0.07380273, -0.07100239,
       -0.06347447, -0.06347447, -0.06808937, -0.06020505, -0.06186103,
       -0.07380273, -0.06347447, -0.06347447, -0.05494284, -0.06020505,
       -0.06658601, -0.06186103, -0.06808937, -0.06658601, -0.06020505,
       -0.06347447, -0.06186103, -0.06658601, -0.0585029 , -0.06

In [11]:
svr_poly.predict([X_test[0]])  # predict mein data 2D mein diya h

array([72.39969291])

In [12]:
predicted_value=svr_poly.predict(X_test)
predicted_value

array([72.39969291, 72.60601427, 69.56953515, ..., 37.61351073,
       62.02379555, 64.82494686])

In [13]:
y_test

1473     52.00
6122     64.00
5875     37.00
2682     99.39
4442     95.00
         ...  
5384    224.00
4005    215.00
4786     73.50
1569     75.00
591      55.00
Name: price, Length: 2136, dtype: float64

In [14]:
from sklearn.metrics import mean_squared_error
import numpy as np
mse=mean_squared_error(y_test,predicted_value)
rmse=np.sqrt(mse)
mse,rmse

(1853.3817059876144, 43.05091992034101)

In [ ]:
#----------------------------------------svc---------------------------------

In [2]:
from sklearn.datasets import load_breast_cancer
data=load_breast_cancer()

In [16]:
data.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [17]:
data.feature_names  #input vars

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [18]:
data.target #target var ki values

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [19]:
data.target_names  # return class of target var

#melignant (0) ->breast cancer
#benign (1) ->no breast cancer

array(['malignant', 'benign'], dtype='<U9')

In [3]:
df=pd.DataFrame(np.c_[data.data,data.target],columns=list(data.feature_names)+['target'])
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890     0.0  
1          0.2750                  0.08902     0.0  
2          0.3613                  0.08758     0.0  
3          0.6638                  0.17300     0.0  
4          0.2364                  0.07678     0.0  

[5 rows x 31 columns]

In [4]:
X=df.iloc[:,0:-1]
y=df.iloc[:,-1]

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.3,random_state=58)

In [6]:
from sklearn.svm import SVC

In [26]:
classification_rbf=SVC(kernel='rbf')
classification_rbf.fit(X_train,y_train)
classification_rbf.score(X_test,y_test)

0.9181286549707602

In [27]:
#feature scaling  ->it must be done as our model does not perform well
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(X_train)
X_train=sc.transform(X_train)
X_test=sc.transform(X_test)

In [28]:
classification_rbf_2=SVC(kernel='rbf')
classification_rbf_2.fit(X_train,y_train)
classification_rbf_2.score(X_test,y_test)

0.9824561403508771

In [30]:
classification_poly=SVC(kernel='poly',degree=2)
classification_poly.fit(X_train,y_train)
classification_poly.score(X_test,y_test)

0.8245614035087719

In [31]:
classification_sig=SVC(kernel='sigmoid',degree=2)
classification_sig.fit(X_train,y_train)
classification_sig.score(X_test,y_test)

0.9415204678362573

In [7]:
classification_lin=SVC(kernel='linear')
classification_lin.fit(X_train,y_train)
classification_lin.score(X_test,y_test)

0.9766081871345029

In [8]:
patient1=[17.99,10.38,122.8,1001.0,.1184,.2776,.3001,.1471,.07871,1.095,.9053,8.589,153.4,.006399,.04904,.05373,.01587,.03003,.006193,25.38,17.33,184.6,2019.0,.1622,.6656,.7119,.2654,.4601,.1189,.1189]
patient1=np.array([patient1])

In [35]:
patient1_sc=sc.transform(patient1)

In [36]:
classification_lin.predict(patient1_sc)

array([1.])

In [9]:
#------------------------------------------- saving and loading model

# serialization: saving the trained model in a file

import joblib
joblib.dump(classification_lin,'svc_model.pkl',compress=3)   # dump() -> perform serialization

# pickle format file(.pkl)  : file in binary format

['svc_model']

In [10]:
model=joblib.load('svc_model.pkl')

In [11]:
model.predict(patient1)

array([1.])

In [12]:
model.score(X_test,y_test)

0.9766081871345029