In [28]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten,Embedding

In [29]:
reviews=[                   # it contains reviews/text of customers
    'nice food',
    'amazing restaurant',
    'too good',
    'just love it!',
    'will go again',
    'horrible food',
    'never go there',
    'poor service',
    'poor quality',
    'needs improvement'
]
sentiments = np.array([1,1,1,1,1,0,0,0,0,0])  # 1:positive review   0:negative review

In [30]:
one_hot('amazing restaurant', 50)  # it uses the hashing function to give hash value to each word of txt

[46, 49]

In [31]:
vocab_size=50   # vocabulary size
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
encoded_reviews

[[1, 20],
 [46, 49],
 [47, 8],
 [19, 49, 30],
 [10, 13, 30],
 [28, 20],
 [41, 13, 25],
 [35, 8],
 [35, 39],
 [24, 14]]

In [32]:
max_length = 3      # max length of text
padded_reviews = pad_sequences(encoded_reviews,maxlen= max_length,padding = 'post')
padded_reviews

# post: to add 0 at end

array([[ 1, 20,  0],
       [46, 49,  0],
       [47,  8,  0],
       [19, 49, 30],
       [10, 13, 30],
       [28, 20,  0],
       [41, 13, 25],
       [35,  8,  0],
       [35, 39,  0],
       [24, 14,  0]])

In [33]:
embedded_vector_size=4

model = Sequential()
model.add(Embedding(vocab_size,embedded_vector_size,input_length=max_length,name = 'my_embedding'))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))

# name='my_embedding'  : give name to the embedding layer

In [34]:
X=padded_reviews
y=sentiments

In [35]:
model.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 3, 4)              200       
_________________________________________________________________
flatten_1 (Flatten)          (None, 12)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 13        
Total params: 213
Trainable params: 213
Non-trainable params: 0
_________________________________________________________________


In [36]:
model.fit(X,y,epochs=50,verbose=0)

In [37]:
loss, accuracy = model.evaluate(X,y)
accuracy

1/1 [==============================] - 0s 238ms/step - loss: 0.6232 - accuracy: 1.0000


1.0

In [38]:
weights = model.get_layer('my_embedding').get_weights()[0]
weights

array([[-0.0595811 , -0.09999812,  0.03581629, -0.01633371],
       [ 0.08459947, -0.08113127, -0.06003959,  0.05226629],
       [ 0.01712458, -0.04731737, -0.03295515,  0.04195899],
       [ 0.03578093,  0.04679969, -0.03319222,  0.01463424],
       [-0.01852079,  0.0092247 , -0.00520384, -0.02587473],
       [-0.03097534, -0.00061309,  0.04115982,  0.00413565],
       [-0.00529651, -0.04902903, -0.04293429,  0.03544048],
       [-0.02760637, -0.02175758,  0.0205819 ,  0.02667412],
       [ 0.01608614,  0.01991251,  0.00078584, -0.08140296],
       [-0.01979166,  0.00162553, -0.01712204,  0.0158349 ],
       [ 0.01831683, -0.02660553, -0.00774319,  0.04657534],
       [ 0.02409576,  0.01233699,  0.0396965 ,  0.02652096],
       [-0.04370281, -0.02420809, -0.00591116, -0.01265679],
       [-0.05494756, -0.0206861 ,  0.04141212,  0.00343948],
       [ 0.07944454, -0.04065689, -0.07161203,  0.05588605],
       [-0.01488612,  0.02989388, -0.04397311,  0.00634571],
       [ 0.04355593,  0.

In [39]:
len(weights)

50

In [40]:
weights[1]  #  1-->'nice'

array([ 0.08459947, -0.08113127, -0.06003959,  0.05226629], dtype=float32)

In [41]:
weights[46]  # 46-->'amazing'

array([ 0.01010624, -0.07726505, -0.05935517,  0.07921765], dtype=float32)